services:
  - type: pserv
    name: mongodb
    runtime: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
  - type: web
    name: nodejs
    runtime: docker
    dockerfilePath: ./api/Dockerfile

